## Naive Bayes Machine Learning Algorithm Implementation

In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [2]:
X, y = load_iris(return_X_y=True)

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=0)

In [4]:
X_train

array([[5. , 2. , 3.5, 1. ],
       [6.5, 3. , 5.5, 1.8],
       [6.7, 3.3, 5.7, 2.5],
       [6. , 2.2, 5. , 1.5],
       [6.7, 2.5, 5.8, 1.8],
       [5.6, 2.5, 3.9, 1.1],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.3, 4.7, 1.6],
       [5.5, 2.4, 3.8, 1.1],
       [6.3, 2.7, 4.9, 1.8],
       [6.3, 2.8, 5.1, 1.5],
       [4.9, 2.5, 4.5, 1.7],
       [6.3, 2.5, 5. , 1.9],
       [7. , 3.2, 4.7, 1.4],
       [6.5, 3. , 5.2, 2. ],
       [6. , 3.4, 4.5, 1.6],
       [4.8, 3.1, 1.6, 0.2],
       [5.8, 2.7, 5.1, 1.9],
       [5.6, 2.7, 4.2, 1.3],
       [5.6, 2.9, 3.6, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [6.1, 3. , 4.6, 1.4],
       [7.2, 3.2, 6. , 1.8],
       [5.3, 3.7, 1.5, 0.2],
       [4.3, 3. , 1.1, 0.1],
       [6.4, 2.7, 5.3, 1.9],
       [5.7, 3. , 4.2, 1.2],
       [5.4, 3.4, 1.7, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [6.9, 3.1, 4.9, 1.5],
       [4.6, 3.1, 1.5, 0.2],
       [5.9, 3. , 5.1, 1.8],
       [5.1, 2.5, 3. , 1.1],
       [4.6, 3.4, 1.4, 0.3],
       [6.2, 2

In [5]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)

GaussianNB()

In [6]:
y_pred = gnb.predict(X_test)

In [7]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]


In [8]:
import seaborn as sns

In [9]:
df = sns.load_dataset('tips')

In [10]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [11]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [12]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [13]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [14]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [15]:
X = df[['total_bill', 'tip', 'sex', 'day', 'time', 'size']]
y=df['smoker']

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [17]:
X.head()

total_bill   tip     sex  day    time  size
0       16.99  1.01  Female  Sun  Dinner     2
1       10.34  1.66    Male  Sun  Dinner     3
2       21.01  3.50    Male  Sun  Dinner     3
3       23.68  3.31    Male  Sun  Dinner     2
4       24.59  3.61  Female  Sun  Dinner     4

In [18]:
type(X)

pandas.core.frame.DataFrame

In [19]:
type(y)

pandas.core.series.Series

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.25, random_state=10)

In [21]:
X_train

total_bill   tip     sex   day    time  size
58        11.24  1.76    Male   Sat  Dinner     2
1         10.34  1.66    Male   Sun  Dinner     3
2         21.01  3.50    Male   Sun  Dinner     3
68        20.23  2.01    Male   Sat  Dinner     2
184       40.55  3.00    Male   Sun  Dinner     2
..          ...   ...     ...   ...     ...   ...
64        17.59  2.64    Male   Sat  Dinner     3
15        21.58  3.92    Male   Sun  Dinner     2
228       13.28  2.72    Male   Sat  Dinner     2
125       29.80  4.20  Female  Thur   Lunch     6
9         14.78  3.23    Male   Sun  Dinner     2

[183 rows x 6 columns]

In [22]:
## OneHot Encoding --> Column transformer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [23]:
categorical_features = ['sex', 'day', 'time']

ct = ColumnTransformer(
    transformers=[
        (
            'ohe',                                     # Name of the step
            OneHotEncoder(drop='first', sparse_output=False), # The transformer
            categorical_features                       # Columns to apply it to
        )
    ],
    remainder='passthrough' # IMPORTANT: Keep total_bill, tip, and size
)

In [24]:
import sys
import numpy as np
np.set_printoptions(threshold=sys.maxsize)
X_train = ct.fit_transform(X_train)

In [31]:
X_train.head()

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [25]:
X_test = ct.transform(X_test)

In [26]:
feature_names = ct.get_feature_names_out()

In [27]:
feature_names

array(['ohe__sex_Male', 'ohe__day_Sat', 'ohe__day_Sun', 'ohe__day_Thur',
       'ohe__time_Lunch', 'remainder__total_bill', 'remainder__tip',
       'remainder__size'], dtype=object)

In [28]:
##Train the model
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(X_train,y_train)

GaussianNB()

In [29]:
y_pred_tips  = gnb.predict(X_test)

In [30]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print(accuracy_score(y_test, y_pred_tips))
print(classification_report(y_test, y_pred_tips))
print(confusion_matrix(y_test, y_pred_tips))

0.6065573770491803
              precision    recall  f1-score   support

          No       0.62      0.73      0.67        33
         Yes       0.59      0.46      0.52        28

    accuracy                           0.61        61
   macro avg       0.60      0.60      0.59        61
weighted avg       0.60      0.61      0.60        61

[[24  9]
 [15 13]]
