### Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [2]:
import numpy as np

#create arrays using numpy
#create 1D array

arr1 = np.array([1,2,3,4,5,6])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


In [3]:
arr2 = np.array([1,2,3,4,5,6])
# arr2.reshape(1,6) #1 Row and 6 Columns
arr2.reshape(2,3) #2 rows and 3 columns

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
#2D Array
arr2 = np.array([[1,2,3,4,5],[4,5,6,7,8]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [4 5 6 7 8]]
(2, 5)


In [5]:
np.arange(2,10,2).reshape(2,2)

array([[2, 4],
       [6, 8]])

In [6]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
#Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
arr = np.array([[1,2,3],[4,5,6]])

print('Array: \n', arr)
print('Shape: ', arr.shape)
print('Number of dimensions: ', arr.ndim)
print('Size (number of elements): ', arr.size)
print('Data type: ', arr.dtype)
print('Item size (in bytes)', arr.itemsize)

Array: 
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number of dimensions:  2
Size (number of elements):  6
Data type:  int64
Item size (in bytes) 8


In [9]:
#Numpy vectorized operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

#Element wise addition
print("Addition: ", arr1 + arr2)

#Element wise subtraction
print("Subtraction: ", arr1 - arr2)

#Element wise multiplication
print("Multiplication: ", arr1 * arr2)

#Element wise division
print("Division: ", arr1 / arr2)

Addition:  [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


In [12]:
#Universal functions
arr = np.array([2,3,4,5,6])

##square root
print(np.sqrt(arr))

##Exponential
print(np.exp(arr))

#Sine
print(np.sin(arr))

#natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [13]:
#array slicing and indexing
arr = np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12]])
print("Array: \n", arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
print(arr[0][0])

1


In [20]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [27]:
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [29]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [30]:
#Modify array elements
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [31]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [34]:
##statistical concepts - Normalization
##to have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

#calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

#Normalize the data
normalized_data = (data-mean)/std_dev
print("Normalized data: ", normalized_data)

Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [36]:
print("Mean: ", mean)
print("Standard Deviation: ", std_dev)
print(np.mean(normalized_data))
print(np.std(normalized_data))

Mean:  3.0
Standard Deviation:  1.4142135623730951
0.0
0.9999999999999999


In [39]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

#Mean
mean = np.mean(data)
print("Mean: ", mean)

#Median
median = np.median(data)
print("Median: ", median)

#Standard Deviation
std_dev = np.std(data)
print("Standard Deviation: ", std_dev)

#Variance
variance = np.var(data)
print("Variance: ", variance)

Mean:  5.5
Median:  5.5
Standard Deviation:  2.8722813232690143
Variance:  8.25


In [42]:
##Logical Operations
data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]


array([5, 6, 7, 8])