# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [1]:
import numpy as np

from DataAnalysiswithPython.matplotlib import sizes

from DataAnalysiswithPython.numpysolutions import corners

In [10]:
#solution 1
array = np.random.randint(1,21,size=(5,5))
print("Original array: ")
print(array)

array[:,2] = 1
print(array)

Original array: 
[[13  5 17 19 15]
 [11  3 14 14  3]
 [ 5  6 12 13  8]
 [18  8 14  9  2]
 [ 3 14 13  3 10]]
[[13  5  1 19 15]
 [11  3  1 14  3]
 [ 5  6  1 13  8]
 [18  8  1  9  2]
 [ 3 14  1  3 10]]


In [21]:
#Solution 2
array1=np.arange(1,17).reshape((4,4))
print("Original array1: ")
print(array1)

# for i in range(4):
#     array1[i,i] = 0
#
np.fill_diagonal(array1,0)
print(array1)

Original array1: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [27]:
#Solution 3
array3 = np.arange(1,37).reshape((6,6))
print("Original array3: ")
print(array3)


subarr1 = array3[2:5,1:4]
print("subarr1: ")
print(subarr1)


Original array3: 
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
subarr1: 
[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [37]:
#Solution 4
array4=np.random.randint(1,21, size=(5,5))

border_arr = np.concatenate((array4[0,:], array4[-1,:], array4[1:-1,0], array4[1:-1,-1]))
print("border_arr: ")
print(border_arr)

border_arr: 
[14  5  8 18 16 19 13  2 16 18  9 11  2 17  7  8]


In [45]:
#Solution 5
arr1 = np.random.randint(1,21,size=(3,4))
arr2 = np.random.randint(1,21,size=(3,4))

print("arr1: ")
print(arr1)
print("arr2: ")
print(arr2)

print("Addition: \n", np.add(arr1, arr2))
print("Subtraction: \n", np.subtract(arr1, arr2))
print("Multiply: \n", np.multiply(arr1, arr2))
print("Division: \n", np.divide(arr1, arr2))

addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2

print("Element-wise addition:")
print(addition)
print("Element-wise subtraction:")
print(subtraction)
print("Element-wise multiplication:")
print(multiplication)
print("Element-wise division:")
print(division)

arr1: 
[[ 1  4  9  6]
 [18  2 15 19]
 [19  4  2  1]]
arr2: 
[[ 6 18  4 18]
 [ 1  4  8 18]
 [15  9 14  3]]
Addition: 
 [[ 7 22 13 24]
 [19  6 23 37]
 [34 13 16  4]]
Subtraction: 
 [[ -5 -14   5 -12]
 [ 17  -2   7   1]
 [  4  -5 -12  -2]]
Multiply: 
 [[  6  72  36 108]
 [ 18   8 120 342]
 [285  36  28   3]]
Division: 
 [[ 0.16666667  0.22222222  2.25        0.33333333]
 [18.          0.5         1.875       1.05555556]
 [ 1.26666667  0.44444444  0.14285714  0.33333333]]
Element-wise addition:
[[ 7 22 13 24]
 [19  6 23 37]
 [34 13 16  4]]
Element-wise subtraction:
[[ -5 -14   5 -12]
 [ 17  -2   7   1]
 [  4  -5 -12  -2]]
Element-wise multiplication:
[[  6  72  36 108]
 [ 18   8 120 342]
 [285  36  28   3]]
Element-wise division:
[[ 0.16666667  0.22222222  2.25        0.33333333]
 [18.          0.5         1.875       1.05555556]
 [ 1.26666667  0.44444444  0.14285714  0.33333333]]


In [46]:
#Solution 6
arr = np.arange(1,17).reshape((4,4))
print("Original array: ")
print(arr)

row_sum = np.sum(arr, axis=1)
column_sum = np.sum(arr, axis=0)

print("Row sum: ")
print(row_sum)
print("Column sum: ")
print(column_sum)


Original array: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row sum: 
[10 26 42 58]
Column sum: 
[28 32 36 40]


In [51]:
#Solution 7
nums = np.random.randint(1,31,size=(5,5))
print("Nums \n",nums)

print("Median: ", np.median(nums))
print("Mean: ", np.mean(nums))
print("Standard Deviation",np.std(nums))
print("Variance: ", np.var(nums))

Nums 
 [[ 1  9  5 23 21]
 [22 28 22 24 17]
 [ 8  1  7 21 19]
 [ 5 21  2 12 19]
 [10 19 10 17 14]]
Median:  17.0
Mean:  14.28
Standard Deviation 7.830810941403196
Variance:  61.32160000000001


In [56]:
array2 = np.arange(1,10).reshape((3,3))
print("Original array2: ")
print(array2)

#Normalize the array
mean = np.mean(array2)
standard_deviation = np.std(array2)

normalized = (array2-mean)/standard_deviation
print("Normalized array2: ")
print(normalized)

Original array2: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized array2: 
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [53]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
array = np.random.randint(1,11, size=(3,3))
row_array = np.random.randint(1,11, size=(3,))
print("Original Array 2D \n", array)
print("Row array 1D \n", row_array)

# Add the 1D array to each row of the 2D array using broadcasting
result = array+row_array
print("Result\n", result)

Original Array 2D 
 [[1 9 3]
 [1 7 1]
 [3 7 3]]
Row array 1D 
 [ 3  8 10]
Result
 [[ 4 17 13]
 [ 4 15 11]
 [ 6 15 13]]


In [61]:
array = np.random.randint(1,11, size=(4,4))
column_array = np.random.randint(1,11, size=(4,))
print("Original Array 2D \n", array)
print("Column array 1D \n", column_array)

# Subtract the 1D array from each column of the 2D array using broadcasting
result = array - column_array[:,np.newaxis]
print("Result\n", result)

Original Array 2D 
 [[ 8  8  6  2]
 [ 9  2  7  4]
 [ 1 10  7  7]
 [ 3  7  5  7]]
Column array 1D 
 [6 4 2 2]
Result
 [[ 2  2  0 -4]
 [ 5 -2  3  0]
 [-1  8  5  5]
 [ 1  5  3  5]]


In [65]:
matrix = np.random.randint(1,11, size=(3,3))
print("Original Array 2D \n", matrix)

#determinant using np linearalgebra functions
determinent = np.linalg.det(matrix)
print("Determinent: ", determinent)

#Inverse of matrix
inverse = np.linalg.inv(matrix)
print("Inverse\n",inverse)

#Eigenvalues
eigen = np.linalg.eigvals(matrix)
print("Eigen Values:\n", eigen)

Original Array 2D 
 [[2 2 9]
 [1 2 9]
 [1 1 7]]
Determinent:  5.000000000000001
Inverse
 [[ 1.  -1.   0. ]
 [ 0.4  1.  -1.8]
 [-0.2  0.   0.4]]
Eigen Values:
 [9.83111869+0.j         0.58444065+0.40867865j 0.58444065-0.40867865j]


In [68]:
array1 = np.random.randint(1,11, size=(3,4))
array2 = np.random.randint(1,11, size=(4,3))

print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

multiplication_result = np.dot(array1, array2)
print("Multiplication result: \n", multiplication_result)

Array 1:
[[ 4  7 10  3]
 [10  8  7  4]
 [ 4  8  6  8]]
Array 2:
[[ 6  7 10]
 [ 1  9 10]
 [ 3  9 10]
 [ 8  3  8]]
Multiplication result: 
 [[ 85 190 234]
 [121 217 282]
 [114 178 244]]


In [71]:
newarray = np.arange(1,10).reshape((3,3))
print("Original Array 2D \n", newarray)

reshape1 = newarray.reshape(1,9)
print("Reshaped array: \n", reshape1)

reshape2 = newarray.reshape(9,1)
print("Reshaped array: \n", reshape2)

Original Array 2D 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped array: 
 [[1 2 3 4 5 6 7 8 9]]
Reshaped array: 
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [74]:
array = np.random.randint(1,11, size=(5,5))
print("Original Array 2D \n", array)

flatten_array = array.flatten()
print("Flattened array: \n", flatten_array)

reshaped_array = flatten_array.reshape(5,5)
print("Reshaped array: \n", reshaped_array)

Original Array 2D 
 [[ 3  6  3  8  2]
 [ 6  2  4  3  3]
 [ 2 10 10  5  8]
 [ 8  5  6  4  8]
 [ 7  7  3  6  8]]
Flattened array: 
 [ 3  6  3  8  2  6  2  4  3  3  2 10 10  5  8  8  5  6  4  8  7  7  3  6
  8]
Reshaped array: 
 [[ 3  6  3  8  2]
 [ 6  2  4  3  3]
 [ 2 10 10  5  8]
 [ 8  5  6  4  8]
 [ 7  7  3  6  8]]


In [77]:
array = np.random.randint(1,21, size=(5,5))
print("Original Array 2D \n", array)


corners = array[[0,0,-1,-1],[0,-1,0,-1]]
print("Corners: \n", corners)

Original Array 2D 
 [[ 1  3  1 19  8]
 [ 9  4 12 16 13]
 [ 2 18 20 14  8]
 [17 18 15  8  1]
 [10 12 20 12 13]]
Corners: 
 [ 1  8 10 13]


In [79]:
array = np.random.randint(1,21,size=(4,4))
print("Original Array 2D \n", array)

array[array>10] = 10
print("Modified array:")
print(array)

Original Array 2D 
 [[ 7  1 10 13]
 [19  3  9 12]
 [ 1 11  8 13]
 [11  4  7 20]]
Modified array:
[[ 7  1 10 10]
 [10  3  9 10]
 [ 1 10  8 10]
 [10  4  7 10]]


In [80]:
data_types = [('name','U10'),('age','i4'),('weight','f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_types)
print("Data \n", data)

Data 
 [('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]


In [81]:
sorted_data = np.sort(data, order='age')

In [83]:
print(sorted_data)

[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


In [87]:
data_types = [('x','i4'),('y','i4')]
data = np.array([(1,2),(3,4),(5,6)], dtype=data_types)
print("Data \n", data)

distances = np.sqrt((data['x'][:,np.newaxis] - data['x'])**2  + (data['y'][:,np.newaxis] - data['y'])**2 )
print("Distances \n", distances)

Data 
 [(1, 2) (3, 4) (5, 6)]
Distances 
 [[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


In [88]:
import numpy.ma as ma

# Create a masked array of shape (4, 4) with random integers
array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 10)
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Compute the sum of the unmasked elements
sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

Original array:
[[19 12 16  8]
 [ 8  9 19  7]
 [12 10 16  3]
 [ 4 15  9 20]]
Masked array:
[[-- -- -- 8]
 [8 9 -- 7]
 [-- 10 -- 3]
 [4 -- 9 --]]
Sum of unmasked elements: 58


In [89]:
# Create a masked array of shape (3, 3) with random integers
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Replace the masked elements with the mean of the unmasked elements
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)

Original array:
[[15 12  7]
 [20 19  4]
 [15 20  8]]
Masked array:
[[-- 12 7]
 [20 -- 4]
 [15 20 --]]
Modified masked array:
[[13 12  7]
 [20 13  4]
 [15 20 13]]
